<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <RootNamespace>Multiplayer.Common</RootNamespace>
    <AssemblyName>MultiplayerChatCommandContracts</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Label="Normalise stack trace file locations">
    <PathMap>$(NuGetPackageRoot)=nuget/,$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=$(AssemblyName)/</PathMap>
  </PropertyGroup>

</Project>
